#server:
#  port: 8035
#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      profile: dev
#      uri: http://${CONFIGSERVER}:${CONFIGPORT}/
#      discovery:
#        enabled: true
#        service-id: config-server
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://${EUREKA01Name}:${EUREKA01Port}/eureka/, http://${EUREKA02Name}:${EUREKA02Port}/eureka/
