server:
  port: 8010
spring:
  application:
    name: consumer01
eureka:
  instance:
    hostname: consumer01
  client:
#    registerWithEureka: false #不注册到Eureka,不在注册中心显示¿
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://${EUREKA01Name}:${EUREKA01Port}/eureka/, http://${EUREKA02Name}:${EUREKA02Port}/eureka/
feign:
  hystrix:
    enabled: true
