server:
  port: 8020
spring:
  application:
    name: ZuulGateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://${EUREKA01Name}:${EUREKA01Port}/eureka/, http://${EUREKA02Name}:${EUREKA02Port}/eureka/
zuul:
  routes:
    consumer01: /user01/**
#  prefix: /zuul
#  ignored-services: "*"  #让其它链接失效