server:
  port: ${PORT}

spring:
  application:
    name: ${HOSTNAME}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenshuran/spring_cloud_test.git
          search-paths: config

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA01Name}:${EUREKA01Port}/eureka/, http://${EUREKA02Name}:${EUREKA02Port}/eureka/